### ISSUE TITLE
Issue with synced storage when using on multiple devices

### ISSUE THREAD

**Issue by danielptv** [danielptv/bookmark-bar-switcher#194]
### Description

According to a review in the Chrome Web Store, the extension does not work properly when using it on multiple devices. Probably, this is an issue with the synced storage.

See the original comment by _Dali U._:

> Amazing tool, should be integrated in chrome as a standard function. Unfortunately it stopped working. I work on a mac and a windows machine. Since a week, everytime i switch computers, all bookmarks are combined in one location and my two generated folder are empty. have to refill them everytime from start...resets again. if this wouldn happen, i would give 5 stars

### Reproduction

Switching between Mac and Windows device and using the extension.

### Environment

Mac and Windows.

**Comment by bartosz145762** [comment]
I have the same issue but when switching between my Windows laptop and Windows desktop. It seems that the extension remembers the last used bookmark bar. For example, when I switch to a private desktop from my work laptop and have the private bookmarks bar enabled, the extension thinks I'm still using the work one. When I click that I want to use the other one, it mixes them both.

**Comment by danielptv** [comment]
My assumption is that the fallback to local storage is the cause of this issue. Probably, it needs to be removed. I will investigate as soon as I find time.

**Comment by ksbach** [comment]
I am encountering the same or a similar issue. I switch back and forth between a Windows desktop and a Macbook. I have two bookmark bars, Personal and Work. When I click Personal the bookmark bar is empty, but when I switch to Work, the bookmark bar contains the bookmarks from both bars.

**Comment by danielptv** [comment]
@ksbach @bartosz145762 I have attempted to fix this issue in #213. It would be awesome if you could test whether or not it actually fixes the problem. You can do so by following the below procedure:

1. Disable the extension downloaded from the web store on both devices.
2. Upload and use the development version of the extension attached to this comment by following this [guide](https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked).

The attached [.zip file](https://github.com/danielptv/bookmark-bar-switcher/files/13695577/bookmark-bar-switcher.zip) contains the state of the code from #213. Feel free to package yourself if you prefer.

[bookmark-bar-switcher.zip](https://github.com/danielptv/bookmark-bar-switcher/files/13695577/bookmark-bar-switcher.zip)

**Comment by bartosz145762** [comment]
I tested it again, and unfortunately, the problem still occurs. From what I've noticed, bars only merge when I leave a different bar open on the laptop than on the desktop, and vice versa. Additionally, I found another issue with the new version - the 'Switch to x bookmark bar.' shortcuts don't work. However, the 'Switch to next/previous bookmark bar.' seems fine.

**Comment by danielptv** [comment]
I have fixed the issue with the shortcut in #235, thank you for mentioning. 

Also thanks a lot for the detailed reproduction of the problem. It helped me understand the underlying issue which has to do with the usage of synced storage in general.

**Comment by danielptv** [comment]
@bartosz145762 @ksbach  could you please test once again? The extension now doesn't use synced storage so the bars hopefully should not get merged any longer. Thank you in advance.

[bookmark-bar-switcher.zip](https://github.com/danielptv/bookmark-bar-switcher/files/13712289/bookmark-bar-switcher.zip)

**Comment by danielptv** [comment]
Great, let me know once you have tested on a second device.

To my understanding, this issue was the fact that the second device "doesn't know" that the bookmarks in the Bookmarks Bar belong to a different bar than the one stored in synced storage that was left open on another device. Therefore, the bookmarks were getting merged. Without using synced storage each device now has an own context that doesn't get interfered with by other devices. 

The downside of course is that you don't have the same bookmarks bar open on all devices.  Sadly, I do not have an idea how I could resolve this as there is no such thing as bookmarks metadata where I could save which bar is the currently active one and therefore have to rely on using browser storage.

**Comment by ksbach** [comment]
Hi Daniel,

Seems to work on my Macbook at home as well. Thanks!

**Comment by bartosz145762** [comment]
Seems to be working fine now :) However, the shortcut still isn't working, but that's not a big deal.

**Comment by bartosz145762** [comment]
@danielptv 
EDIT: I still have the same issues as before, you wrote that bars shouldn't sync between devices, however when i switch bars on laptop it also switches on desktop and vice versa, Shortcut still doesn't work, maybe you accidentally linked older version?

**Comment by danielptv** [comment]
@bartosz145762 interesting, I will have another look into this. Are you using the version published to the Chrome Web Store? There I have published the fixes for this issue as well as the fix for the broken shortcut that you had mentioned.

Another question: Could you please provide me your sync settings (`Settings` > `Sync and Google Services` > `Manage what you sync`)? This would help me further investigate the issue.

For example, mine look like this:
![image](https://github.com/danielptv/bookmark-bar-switcher/assets/93288603/1afbd798-32df-477f-ba34-9de3db35e1be)

Do you have `Sync everything` enabled, too?

**Comment by bartosz145762** [comment]
I tried both, Chrome Web Store one and the one you uploaded couple of comments above. I am still experiencing merge issue on both but Web Store one doesn't have shortcut issue. I have the same Chrome settings as you do.

**Comment by ksbach** [comment]
Hi Daniel,

I am also experiencing the original issue again. I have Sync everything
turned on.

Thanks,
Kevin

**Comment by Kamiikaze** [comment]
Hey guys, maybe there is still a issue with the sync storage as I figured out storages doesn't get cleaned by removing the extension.

Could you try these these to delete the local and sync storage of the extension.

https://github.com/danielptv/bookmark-bar-switcher/issues/213#issuecomment-1854465947

**Comment by jkeegan** [comment]
Having the same issue as everyone else here - now only one of my bookmark bars works, and it contains everything from both bookmark bars squashed into one. My use case was a home laptop using Chrome and a work laptop using Chrome, and two bookmark bars (home and work). Back when it worked, opening my home laptop I'd still sometimes be on the "work" bar but that was ok I'd just switch (as much as I'd wished that the tool could somehow know from some local file "which" laptop it was on and which bar to use or default to).

When it broke, I ended up with three bookmark bars somehow (I did something manual to try to address it, because they're called "Home Bookmark Bar", "Work (xyzcompany) Bookmark Bar", and "Work (xyzcompany) Bookmark Bar old", which I vaguely remember doing). The "Home Bookmark Bar" one is now populated with my work bookmark bar followed by by home bookmark bar.

Is there any advice on what to do to repair a broken bookmark bar? What is the json schema supposed to look like in the Bookmarks file? Happy to manually edit to try to fix it, if your extension doesn't already have some way to see what happened and attempt its own fix?

What's the latest version I should try? Running on version 1.5.1 (it says updated January 2, 2024) on MacOS (both laptops are MacOS).
